module.exports = {
  proadmin: {
    assigned_to: "👤 Assigned To",
    available_codes: "✅ Available ({{count}})",
    available_codes_stat: "✅ Available",
    codes_label: "🎫 Codes",
    days: "{{days}} days",
    dm_description: "Here is your exclusive PRO redemption code:\n\n**Code:** `{{code}}`\n**Duration:** {{duration}}\n\nUse this code in your server with `/pro redeem` to activate PRO features!",
    dm_failed: "❌ Failed",
    dm_footer: "TON618 - Premium Membership",
    dm_sent: "📨 DM Sent",
    dm_title: "🎉 Your PRO Code is Ready!",
    error_title: "❌ Error",
    expired_codes: "⏰ Expired",
    generate_error: "There was an error generating the codes. Please try again.",
    generate_success_description: "Here are your new PRO codes with **{{duration}}** duration:",
    generate_success_title: "✅ Generated {{count}} Code(s)",
    generated_by: "🤖 Generated By",
    how_to_redeem: "How to Redeem",
    lifetime: "Lifetime",
    list_error: "There was an error listing the codes. Please try again.",
    list_title: "📋 PRO Code Inventory",
    no_codes: "No available codes",
    none: "None",
    redeem_instructions: "1. Go to your Discord server\n2. Run `/pro redeem`\n3. Enter your code: `{{code}}`",
    redeemed_codes: "🎟️ Recently Redeemed ({{count}})",
    redeemed_codes_stat: "🎟️ Redeemed",
    slash: {
      description: "Generate and manage PRO redemption codes (Support Server only)",
      generate_description: "Generate new PRO redemption codes",
      list_description: "List available and redeemed codes",
      stats_description: "View code statistics"
    },
    slash_options: {
      count: "Number of codes to generate (1-20)",
      duration: "Duration of the PRO membership",
      for_user: "Optional: User to assign the code to (sends DM)",
      notes: "Optional notes about these codes"
    },
    stats_error: "There was an error fetching statistics. Please try again.",
    stats_title: "📊 PRO Code Statistics",
    total_codes: "🎫 Total Codes",
    valid_until: "⏰ Valid Until"
  }
};
